version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-library
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  redis:
    image: redis:latest
    container_name: redis-library
    hostname: localhost
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no", "--loglevel", "debug"]
    ports:
      - "6379:6379"
    networks:
      - library-network
    
  app:
    build:
      context: ../back-end/library
      dockerfile: Dockerfile
    container_name: library-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - library-network

networks:
  library-network: 
    driver: bridge

volumes:
  postgres-data: 
  redis-data:
